# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99abf35e3d1bf76f56a6c1aeac476784e0bea74472196d0a5856eea983ab79a60284a270269b729b913b9e6c5860bdd4930eb24c1dc14252344a7dc2b9947886

test:
  secret_key_base: a14b51ce2f9f0b1faf1e2b5868a6a2255f2d6122b409f0941d806b4009f95f3c42d6194063b828393bcd14cf76a5753f0785e073b778106c82a5280fcba77b94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
